spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.101:8848
server:
  port: 8020

management:
  endpoints:
    web:
      exposure:
        exclude: "*"